fixed contributor schema
Cyber4All/feature-service pull request #14
Opened 2021-06-02 18:31 UTC by mfranz1

This PR is a part of the clark-client PR 'contributor and hierarchy fixes'. The schema of featured learning objects was updated in order to store a contributors organization.

2021-06-02 18:33 UTC, jmulholland4014 approved these changes

2021-06-02 18:39 UTC, pzalep1 requested changes

2021-06-02 18:39 UTC, pzalep1 commented on src/learning-objects/schemas/learning-objectSchema.ts
> -    username: String,
We can keep the username.

2021-06-02 18:51 UTC, pzalep1 approved these changes

2021-06-02 18:51 UTC, EVogel1999 reviewed
After Paige's comment is addressed looks good!

2021-06-02 18:53 UTC, pzalep1 approved these changes

2021-06-03 12:40 UTC, Cwagne17 approved these changes

2021-06-03 19:55 UTC, merged