Implement SendGrid service for featured Author Emails
Cyber4All/feature-service pull request #9
Opened 2020-09-17 19:37 UTC by davidnso

This PR implements a SendGrid service that can be injected anywhere else on the server for ease of use so that we can expand as things grow and change.

2020-09-17 19:43 UTC, pzalep1 requested changes

2020-09-17 19:43 UTC, pzalep1 commented on src/learning-objects/learning-objects.controller.ts
> +        // await this.learningObjectService.updateAllFeatured(learningObjectDto);
:fire: Comment

2020-09-17 19:43 UTC, pzalep1 commented on src/services/send-grid/send-grid.service.ts
> +                templateVars: {
Depending on where @EVogel1999 created the template these could be dynamic_template_data. Legacy SendGrid templates still use this, but new dynamic templates have a different variable name.

2020-09-17 19:43 UTC, pzalep1 commented on src/services/send-grid/send-grid.service.ts
> +        console.log(error.response.body.errors)
Can we throw this so an error gets reported back?

2020-09-17 19:43 UTC, pzalep1 commented on src/services/send-grid/interfaces/mailer.ts
> +export interface DefaultEmailParams {
Can we also create enums for the templates so we have a place to put template ids? Like here: https://github.com/Cyber4All/cards-service/blob/master/src/shared/interfaces/mailer.defaults.ts

2020-09-17 19:45 UTC, davidnso commented on src/services/send-grid/send-grid.service.ts
> +        console.log(error.response.body.errors)
I'm pretty sure the errors are handled within the service. This was just for easier debugging. It's a little weird

2020-09-17 19:47 UTC, pzalep1 commented on src/services/send-grid/send-grid.service.ts
> +        console.log(error.response.body.errors)
Okay that sounds fine. Nest handles a lot of these errors, but I wasn’t sure if it was meant to be thrown somewhere.

2020-09-18 13:41 UTC, Olaniyan99 commented
apart from the comment Paige pointed out, this is good to go.

2020-09-18 14:30 UTC, EVogel1999 commented on src/learning-objects/learning-objects.controller.ts
> +    // @UseGuards(JwtAuthGuard)
Why is this commented out?

2020-09-18 14:32 UTC, EVogel1999 commented on src/services/send-grid/send-grid.service.ts
> +                templateVars: {
I created it under dynamic templates.  The data needed is located in the design/implementation story for the email.

2020-09-22 19:17 UTC, davidnso commented on src/learning-objects/learning-objects.controller.ts
> +    // @UseGuards(JwtAuthGuard)
I needed to bypass the authgraud. This is uncommented the next commit

2020-09-22 19:26 UTC, pzalep1 approved these changes

2020-09-22 19:26 UTC, pzalep1 commented on src/services/send-grid/interfaces/mailer.defaults.ts
> +TEMPLATE_VARIABLES.set(TEMPLATES.FEATURED_AUTHOR, {
I like this.

2020-09-24 14:53 UTC, EVogel1999 approved these changes

2020-09-24 17:28 UTC, merged